version: "3.7"

services:
  ml-lite:
    container_name: ml-lite_app
    image: lazyoracle/ml-lite:latest
    build:
      args:
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER=${USER}
      context: .
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - ~/ml-notebooks:$HOME/ml-lite/ml-notebooks
    init: true
    stdin_open: true
    tty: true 